version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: coverlet.collector
    versions:
    - 1.3.0
    - 3.0.2
  - dependency-name: Moq
    versions:
    - 4.15.2
    - 4.16.0
  - dependency-name: AWSSDK.SimpleNotificationService
    versions:
    - 3.5.1.28
    - 3.5.1.37
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
