version: '2'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sns

  localstack-setup:
    image: amazon/aws-cli:2.0.24
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=guest
      - AWS_SECRET_ACCESS_KEY=guest
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    command: >
      "
        while ! aws --endpoint-url=http://localstack:4566 sns list-topics > /dev/null; do echo waiting; sleep 5; done;
        aws --endpoint-url=http://localstack:4566 sns create-topic --name TestNotificationTopic                
        aws --endpoint-url=http://localstack:4566 sns list-topics
        echo 'LOCALSTACK-SETUP-DONE!' 
      "

  jaeger:
    image: 'jaegertracing/all-in-one:1.18'
    ports:
        - '5775:5775/udp'
        - '6831:6831/udp'
        - '6832:6832/udp'
        - '5778:5778'
        - '16686:16686'
        - '14268:14268'
        - '14250:14250'
        - '9411:9411'
    environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411