version: '2'
services:
  localstack:
    image: localstack/localstack:0.11.2
    ports:
      - '4576:4576'
    environment:
      - SERVICES=sns
        
  localstack-setup:
    image: amazon/aws-cli:2.0.24
    depends_on:
      - localstack
    hostname: localstack-create-queues
    entrypoint: /bin/sh -c
    command: >
      "
        while ! aws --endpoint-url=http://localstack:4576 sns list-topics > /dev/null; do echo waiting; sleep 3; done;
        aws --endpoint-url=http://localstack:4576 sns create-topic --name TestNotificationTopic
                
        aws --endpoint-url=http://localstack:4576 sns list-topics
        echo 'LOCALSTACK-SETUP-DONE!' 
      "
    environment:
      - AWS_ACCESS_KEY_ID=guest
      - AWS_SECRET_ACCESS_KEY=guest
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT=http://localhost:4576